### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mattdeveluk** [paranerd/simpledrive#3]
Hello,

firstly, I want to thank you for creating this great piece of software ! Secondly, would you please consider adding those features ?
- Public registration option
- Setting storage space limit in admin
- Better file previews in gallery mode (different icon for different file types, image & video previews, file name under file icon).

Thanks.

**Comment by paranerd** [comment]
Hi there,

Thank you very much!
About those features:
(1) I could definitely create a public registration site for you, but
that's not gonna make it in the general release since I wouldn't want sb to
create a user account on my private server... But in a shared-server-setup
that would of course absolutely make sense.

(2) You can actually do that already. Under admin settings just click on
the "Storage total" value for a user to set a limit.

(3) Gallery Mode is for images only (any other filetype is hidden). If you
just want a grid view, just hit the button in the bottom right corner.

Hope that helped.
Have a good day ;-)
